# PyDantic model for Codemeta 3.1
# Generated by Gemini on 28/06/2026
# from https://github.com/codemeta/codemeta/blob/0bc1f26d9575c9bfc288571b358a24a464595443/codemeta.jsonld
# and https://github.com/codemeta/codemeta/blob/0bc1f26d9575c9bfc288571b358a24a464595443/properties_description.csv
# Manual corrections and refactoring by G. Noel

from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, HttpUrl
from models.schemaorg.v30_0 import schemaorg_pydantic as schemaorg

# ----------------------------------------------------------------------
# Nested / Supporting Types from Schema.org and CodeMeta
# ----------------------------------------------------------------------

Agent = schemaorg.Person | schemaorg.Organization

# ----------------------------------------------------------------------
# Main CodeMeta 3.1 Pydantic Model
# ----------------------------------------------------------------------

class Software(schemaorg.SoftwareApplication, schemaorg.SoftwareSourceCode):
    """
    Pydantic Model for CodeMeta 3.1 mapped against schemas found in properties_description.csv
    """
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True
    )

    # JSON-LD Context Fields
    context: Union[str, List[Any]] = Field(
        "https://w3id.org/codemeta/3.1", 
        alias="@context"
    )
    type_: Union[str, List[str]] = Field(
        "SoftwareSourceCode", 
        alias="@type"
    )

    # --- schema:Thing Properties ---
    name: str = Field(..., description="The name of the software")
    url: Optional[Union[HttpUrl, str]] = Field(None, description="URL of the software")

    # CodeMeta Extended Terms (prefixed via 'codemeta:' vocabulary maps)
    softwareSuggestions: Optional[Union[schemaorg.SoftwareSourceCode, HttpUrl, str, List[Union[schemaorg.SoftwareSourceCode, HttpUrl, str]]]] = Field(None, description="Optional dependencies, e.g. for optional features, code development, etc.")
    continuousIntegration: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="A link to continuous integration service")
    buildInstructions: Optional[Union[HttpUrl, str]] = Field(None, description="A link to installation instructions/documentation")
    developmentStatus: Optional[str] = Field(None, description="Description of development status, e.g. active, inactive, suspended. See repostatus.org")
    embargoEndDate: Optional[date] = Field(None, description="Software may be embargoed from public access until a specified date")
    funding: Optional[Union[str, Dict[str, Any], List[Union[str, Dict[str, Any]]]]] = Field(None, description="Funding source (e.g. specific grant)")
    readme: Optional[Union[HttpUrl, str]] = Field(None, description="A link to software Readme file")
    issueTracker: Optional[Union[HttpUrl, str]] = Field(None, description="A link to software bug reporting or issue tracking system")
    referencePublication: Optional[Union[schemaorg.CreativeWork, HttpUrl, str, List[Union[schemaorg.CreativeWork, HttpUrl, str]]]] = Field(None, description="An academic publication related to the software.")
    maintainer: Optional[Union[Agent, List[Agent]]] = Field(None, description="Individual responsible for maintaining the software (usually includes an email contact address)")
    hasSourceCode: Optional[Union[schemaorg.SoftwareSourceCode, HttpUrl, str, List[Union[schemaorg.SoftwareSourceCode, HttpUrl, str]]]] = Field(None, description="A link that states where the software code is for a given software.")
    isSourceCodeOf: Optional[Union[schemaorg.SoftwareApplication, HttpUrl, str, List[Union[schemaorg.SoftwareApplication, HttpUrl, str]]]] = Field(None, description="A link that states where software application is built from a given source code.")

