# PyDantic model for Codemeta 3.0
# Generated by Gemini on 28/06/2026
# from https://github.com/codemeta/codemeta/blob/0bc1f26d9575c9bfc288571b358a24a464595443/codemeta.jsonld

from datetime import date
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, HttpUrl

# ----------------------------------------------------------------------
# Nested / Supporting Types from Schema.org and CodeMeta
# ----------------------------------------------------------------------

class Thing(BaseModel):
    """Base class for structured entities containing common JSON-LD fields."""
    model_config = ConfigDict(populate_by_name=True)
    
    id_: Optional[str] = Field(None, alias="@id")
    type_: Optional[str] = Field(None, alias="@type")


class Organization(Thing):
    type_: str = Field("Organization", alias="@type")
    name: str
    url: Optional[Union[HttpUrl, str]] = None
    address: Optional[str] = None


class Person(Thing):
    type_: str = Field("Person", alias="@type")
    givenName: Optional[str] = None
    familyName: Optional[str] = None
    email: Optional[str] = None
    affiliation: Optional[Union[Organization, str, List[Union[Organization, str]]]] = None


class Review(Thing):
    type_: str = Field("Review", alias="@type")
    reviewAspect: Optional[str] = None
    reviewBody: Optional[str] = None


class Role(Thing):
    type_: str = Field("Role", alias="@type")
    roleName: Optional[str] = None
    startDate: Optional[date] = None
    endDate: Optional[date] = None


# Reusable types since fields frequently accept strings, objects, or lists of either
Agent = Union[Person, Organization, str]
CreativeWork = Union[Dict[str, Any], str]  # Often a citation/reference mapping or URL string


# ----------------------------------------------------------------------
# Main CodeMeta Model
# ----------------------------------------------------------------------

class CodeMeta(Thing):
    """
    Pydantic Model for CodeMeta 3.1 based on the codemeta.jsonld context definition.
    """
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True
    )

    # JSON-LD Context Fields
    context: Union[str, List[Any]] = Field(
        "https://w3id.org/codemeta/3.1", 
        alias="@context"
    )
    type_: Union[str, List[str]] = Field(
        "SoftwareSourceCode", 
        alias="@type"
    )

    # Core Schema.org Core Fields (Overlapping with SoftwareSourceCode / SoftwareApplication)
    name: str = Field(..., description="The name of the software.")
    description: Optional[str] = Field(None, description="A description of the software functionality and purpose.")
    version: Optional[Union[str, float]] = Field(None, description="The version of the software release.")
    softwareVersion: Optional[str] = Field(None, description="An alternate descriptor for the version of the software release.")
    identifier: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="A unique identifier for the software (e.g., a DOI, URL).")
    url: Optional[Union[HttpUrl, str]] = Field(None, description="The URL of the canonical web page for this project.")
    sameAs: Optional[Union[HttpUrl, List[HttpUrl]]] = Field(None, description="URL of a reference web page that unambiguously indicates the item's identity.")
    
    # Dates
    dateCreated: Optional[date] = None
    dateModified: Optional[date] = None
    datePublished: Optional[date] = None
    
    # Classification & Content
    keywords: Optional[Union[str, List[str]]] = Field(None, description="Keywords or tags used to describe this software.")
    applicationCategory: Optional[Union[str, HttpUrl]] = None
    applicationSubCategory: Optional[Union[str, HttpUrl]] = None
    fileFormat: Optional[Union[str, HttpUrl]] = Field(None, description="MIME type or file format description.")
    fileSize: Optional[str] = Field(None, description="Size of the file / package.")
    license: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="The software license (URL or identifier).")
    downloadUrl: Optional[Union[HttpUrl, str]] = None
    installUrl: Optional[Union[HttpUrl, str]] = None
    codeRepository: Optional[Union[HttpUrl, str]] = Field(None, description="Link to the source code repository (e.g., GitHub).")
    
    # People & Roles
    author: Optional[List[Agent]] = Field(None, description="The authors of the software package.")
    contributor: Optional[Union[Agent, List[Agent]]] = Field(None, description="Secondary contributors to the project.")
    editor: Optional[Union[Agent, List[Agent]]] = None
    producer: Optional[Union[Agent, List[Agent]]] = None
    provider: Optional[Union[Agent, List[Agent]]] = None
    publisher: Optional[Union[Agent, List[Agent]]] = None
    sponsor: Optional[Union[Agent, List[Agent]]] = None
    funder: Optional[Union[Agent, List[Agent]]] = None
    copyrightHolder: Optional[Union[Agent, List[Agent]]] = None
    copyrightYear: Optional[int] = None
    
    # Requirements & System Properties
    operatingSystem: Optional[Union[str, List[str]]] = None
    programmingLanguage: Optional[Union[str, Dict[str, Any], List[Union[str, Dict[str, Any]]]]] = Field(None, description="The programming language(s) the software is written in.")
    runtimePlatform: Optional[Union[str, List[str]]] = None
    memoryRequirements: Optional[Union[HttpUrl, str]] = None
    processorRequirements: Optional[Union[str, List[str]]] = None
    storageRequirements: Optional[Union[HttpUrl, str]] = None
    
    # Relations & Academic Context
    citation: Optional[Union[CreativeWork, List[CreativeWork]]] = Field(None, description="Academic citations or related articles.")
    isPartOf: Optional[Union[CreativeWork, List[CreativeWork]]] = None
    hasPart: Optional[Union[CreativeWork, List[CreativeWork]]] = None
    relatedLink: Optional[Union[HttpUrl, List[HttpUrl]]] = None
    supportingData: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = None
    targetProduct: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = None
    encoding: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = None
    permissions: Optional[Union[str, List[str]]] = None
    position: Optional[Union[str, int]] = None
    
    # Review Fields
    review: Optional[Union[Review, List[Review]]] = None
    releaseNotes: Optional[Union[str, HttpUrl]] = None

    # CodeMeta Extended Terms (prefixed via 'codemeta:' vocabulary maps)
    softwareSuggestions: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = None
    continuousIntegration: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="Link to CI system logs/status.")
    buildInstructions: Optional[Union[HttpUrl, str]] = Field(None, description="Link or text providing build setup help.")
    developmentStatus: Optional[Union[HttpUrl, str]] = Field(None, description="Development phase (e.g. active, suspended).")
    embargoEndDate: Optional[date] = None
    funding: Optional[Union[str, Dict[str, Any], List[Union[str, Dict[str, Any]]]]] = Field(None, description="Grant information or funding details.")
    readme: Optional[Union[HttpUrl, str]] = Field(None, description="Link to the README documentation file.")
    issueTracker: Optional[Union[HttpUrl, str]] = Field(None, description="Link to the project bugs / issue tracking system.")
    referencePublication: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="The primary academic paper to cite when using this software.")
    maintainer: Optional[Union[Agent, List[Agent]]] = Field(None, description="The active maintainers of the software project.")
    hasSourceCode: Optional[Union[HttpUrl, str]] = None
    isSourceCodeOf: Optional[Union[HttpUrl, str]] = None
