# PyDantic model for Codemeta 3.1
# Generated by Gemini on 28/06/2026
# from https://github.com/codemeta/codemeta/blob/0bc1f26d9575c9bfc288571b358a24a464595443/codemeta.jsonld
# and https://github.com/codemeta/codemeta/blob/0bc1f26d9575c9bfc288571b358a24a464595443/properties_description.csv
# Manual corrections and refactoring by G. Noel

from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, HttpUrl

# ----------------------------------------------------------------------
# Nested / Supporting Types from Schema.org and CodeMeta
# ----------------------------------------------------------------------

class Thing(BaseModel):
    """Base class for structured entities containing common JSON-LD fields."""
    model_config = ConfigDict(populate_by_name=True)
    id_: Optional[str] = Field(None, alias="@id")
    type_: Optional[str] = Field(None, alias="@type")
    url: Optional[Union[HttpUrl, str]] = None
    identifier: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(
        None, description="URL identifier, ideally an ORCID ID for individuals, a FundRef ID for funders, DOI for dataset / software"
    )
    description: Optional[str] = Field(None, description="A description of the item.")
    sameAs: Optional[Union[HttpUrl, List[HttpUrl]]] = Field(None, description="URL of a reference Web page that unambiguously indicates the item's identity.")
    relatedLink: Optional[Union[HttpUrl, List[HttpUrl]]] = Field(None, description="A link related to this object, e.g. related web pages")

class Organization(Thing):
    type_: str = Field("Organization", alias="@type")
    name: str = Field(..., description="The name of an Organization")
    email: Optional[str] = Field(None, description="Email address")
    address: Optional[str] = Field(None, description="Physical address of the item.")


class Person(Thing):
    type_: str = Field("Person", alias="@type")
    name: Optional[str] = Field(
        None, description="The name of a Person if separate given and family names cannot be resolved"
    )
    email: Optional[str] = Field(None, description="Email address")
    givenName: Optional[str] = Field(None, description="Given name. In the U.S., the first name of a Person.")
    familyName: Optional[str] = Field(None, description="Family name. In the U.S., the last name of an Person.")
    affiliation: Optional[Union[Organization, str, List[Union[Organization, str]]]] = Field(
        None, description="An organization that this person is affiliated with."
    )


class Review(Thing):
    type_: str = Field("Review", alias="@type")
    reviewAspect: Optional[str] = Field(None, description="This review is relevant to this part or facet of the object being review")
    reviewBody: Optional[str] = Field(None, description="The actual body of the review")


class Role(Thing):
    type_: str = Field("Role", alias="@type")
    roleName: Optional[str] = Field(None, description="A role played, performed, or filled by a person or organization.")
    startDate: Optional[Union[date, datetime]] = Field(None, description="The start date and time of the item, usually a Role.")
    endDate: Optional[Union[date, datetime]] = Field(None, description="The end date and time of the item, usually a Role.")


# Generic placeholder objects mapping onto external schemas from properties_description.csv
Agent = Union[Person, Organization, str]

# CreativeWork = Union[Dict[str, Any], str]  # Used for scholarly articles, help docs, citations, etc.

class CreativeWork(Thing):
    author: Optional[Union[Agent, List[Agent]]] = Field(None, description="The author of this content or rating.")
    contributor: Optional[Union[Agent, List[Agent]]] = Field(None, description="A secondary contributor to the CreativeWork or Event.")
    editor: Optional[Union[Agent, List[Agent]]] = Field(None, description="Specifies the Person who edited the CreativeWork.")
    funder: Optional[Union[Agent, List[Agent]]] = Field(None, description="A person or organization that supports something through financial contribution.")
    publisher: Optional[Union[Agent, List[Agent]]] = Field(None, description="The publisher of the creative work.")
    sponsor: Optional[Union[Agent, List[Agent]]] = Field(None, description="A person or organization that supports a thing through a pledge, promise, or financial contribution.")
    producer: Optional[Union[Agent, List[Agent]]] = Field(None, description="The person or organization who produced the work.")
    provider: Optional[Union[Agent, List[Agent]]] = Field(None, description="The service provider, service operator, or service performer.")

    citation: Optional[Union[CreativeWork, HttpUrl, List[Union[CreativeWork, HttpUrl]]]] = Field(None, description="A citation or reference to another creative work.")
    copyrightHolder: Optional[Union[Agent, List[Agent]]] = Field(None, description="The party holding the legal copyright to the CreativeWork.")
    copyrightYear: Optional[Union[int, float]] = Field(None, description="The year during which the claimed copyright for the CreativeWork was first asserted.")

    dateCreated: Optional[date] = Field(None, description="The date on which the CreativeWork was created or the item was added to a DataFeed.")
    dateModified: Optional[date] = Field(None, description="The date on which the CreativeWork was most recently modified.")
    datePublished: Optional[date] = Field(None, description="Date of first broadcast/publication.")
    
    encoding: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = Field(None, description="A media object that encodes this CreativeWork.")
    fileFormat: Optional[Union[str, HttpUrl]] = Field(None, description="Media type, typically MIME format of the content.")
    keywords: Optional[Union[str, List[str]]] = Field(None, description="Keywords or tags used to describe this content.")
    license: Optional[Union[CreativeWork, HttpUrl, str, List[Union[CreativeWork, HttpUrl, str]]]] = Field(None, description="A license document that applies to this content, typically indicated by URL.")
    version: Optional[Union[str, float]] = Field(None, description="The version of the CreativeWork embodied by a specified resource.")
    isAccessibleForFree: Optional[bool] = Field(None, description="A flag to signal that the publication is accessible for free.")
    isPartOf: Optional[Union[CreativeWork, HttpUrl, str, List[Union[CreativeWork, HttpUrl, str]]]] = Field(None, description="Indicates a CreativeWork that this CreativeWork is part of.")
    hasPart: Optional[Union[CreativeWork, HttpUrl, str, List[Union[CreativeWork, HttpUrl, str]]]] = Field(None, description="Indicates a CreativeWork that is a part of this CreativeWork.")
    position: Optional[Union[int, str]] = Field(None, description="The position of an item in a series or sequence of items (used for ordering JSON arrays).")

class SoftwareApplication(CreativeWork):
    applicationCategory: Optional[Union[str, HttpUrl, List[Union[str, HttpUrl]]]] = Field(None, description="Type of software application, e.g. 'Game, Multimedia'.")
    applicationSubCategory: Optional[Union[str, HttpUrl, List[Union[str, HttpUrl]]]] = Field(None, description="Subcategory of the application, e.g. 'Arcade Game'.")
    downloadUrl: Optional[Union[HttpUrl, str]] = Field(None, description="If the file can be downloaded, URL to download the binary.")
    fileSize: Optional[str] = Field(None, description="Size of the application / package (e.g. 18MB).")
    installUrl: Optional[Union[HttpUrl, str]] = Field(None, description="URL at which the app may be installed, if different from the URL of the item.")
    memoryRequirements: Optional[Union[str, HttpUrl]] = Field(None, description="Minimum memory requirements.")
    operatingSystem: Optional[Union[str, List[str]]] = Field(None, description="Operating systems supported (Windows 7, OSX 10.6, Android 1.6).")
    permissions: Optional[Union[str, List[str]]] = Field(None, description="Permission(s) required to run the app.")
    processorRequirements: Optional[Union[str, List[str]]] = Field(None, description="Processor architecture required to run the application (e.g. IA64).")
    softwareHelp: Optional[Union[CreativeWork, List[CreativeWork]]] = Field(None, description="Software application help.")
    softwareRequirements: Optional[Union[SoftwareSourceCode, HttpUrl, str, List[Union[SoftwareSourceCode, HttpUrl, str]]]] = Field(None, description="Required software dependencies")
    softwareVersion: Optional[str] = Field(None, description="Version of the software instance.")
    storageRequirements: Optional[Union[str, HttpUrl]] = Field(None, description="Storage requirements (free space required).")
    supportingData: Optional[Union[Dict[str, Any], List[Dict[str, Any]]]] = Field(None, description="Supporting data for a SoftwareApplication.")
    releaseNotes: Optional[Union[str, HttpUrl]] = Field(None, description="Description of what changed in this version.")

class SoftwareSourceCode(CreativeWork):
    codeRepository: Optional[Union[HttpUrl, str]] = Field(
        None, description="A link to the repository where the un-compiled, human readable code and related code is located."
    )
    programmingLanguage: Optional[Union[str, Dict[str, Any], List[Union[str, Dict[str, Any]]]]] = Field(
        None, description="The computer programming language."
    )
    runtimePlatform: Optional[Union[str, List[str]]] = Field(
        None, description="Runtime platform or script interpreter dependencies. Supersedes runtime."
    )
    targetProduct: Optional[Union[SoftwareApplication, HttpUrl, str, List[Union[SoftwareApplication, HttpUrl, str]]]] = Field(
        None, description="Target Operating System / Product to which the code applies."
    )
    review: Optional[Union[Review, List[Review]]] = Field(None, description="A review of the source code.")


# ----------------------------------------------------------------------
# Main CodeMeta 3.1 Pydantic Model
# ----------------------------------------------------------------------

class Software(SoftwareApplication, SoftwareSourceCode):
    """
    Pydantic Model for CodeMeta 3.1 mapped against schemas found in properties_description.csv
    """
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True
    )

    # JSON-LD Context Fields
    context: Union[str, List[Any]] = Field(
        "https://w3id.org/codemeta/3.1", 
        alias="@context"
    )
    type_: Union[str, List[str]] = Field(
        "SoftwareSourceCode", 
        alias="@type"
    )

    # --- schema:Thing Properties ---
    name: str = Field(..., description="The name of the software")
    url: Optional[Union[HttpUrl, str]] = Field(None, description="URL of the software")

    # CodeMeta Extended Terms (prefixed via 'codemeta:' vocabulary maps)
    softwareSuggestions: Optional[Union[SoftwareSourceCode, HttpUrl, str, List[Union[SoftwareSourceCode, HttpUrl, str]]]] = Field(None, description="Optional dependencies, e.g. for optional features, code development, etc.")
    continuousIntegration: Optional[Union[HttpUrl, str, List[Union[HttpUrl, str]]]] = Field(None, description="A link to continuous integration service")
    buildInstructions: Optional[Union[HttpUrl, str]] = Field(None, description="A link to installation instructions/documentation")
    developmentStatus: Optional[str] = Field(None, description="Description of development status, e.g. active, inactive, suspended. See repostatus.org")
    embargoEndDate: Optional[date] = Field(None, description="Software may be embargoed from public access until a specified date")
    funding: Optional[Union[str, Dict[str, Any], List[Union[str, Dict[str, Any]]]]] = Field(None, description="Funding source (e.g. specific grant)")
    readme: Optional[Union[HttpUrl, str]] = Field(None, description="A link to software Readme file")
    issueTracker: Optional[Union[HttpUrl, str]] = Field(None, description="A link to software bug reporting or issue tracking system")
    referencePublication: Optional[Union[CreativeWork, HttpUrl, str, List[Union[CreativeWork, HttpUrl, str]]]] = Field(None, description="An academic publication related to the software.")
    maintainer: Optional[Union[Person, List[Person]]] = Field(None, description="Individual responsible for maintaining the software (usually includes an email contact address)")
    hasSourceCode: Optional[Union[SoftwareSourceCode, HttpUrl, str, List[Union[SoftwareSourceCode, HttpUrl, str]]]] = Field(None, description="A link that states where the software code is for a given software.")
    isSourceCodeOf: Optional[Union[SoftwareApplication, HttpUrl, str, List[Union[SoftwareApplication, HttpUrl, str]]]] = Field(None, description="A link that states where software application is built from a given source code.")